name: audio_player
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  gap: ^3.0.1
  path_provider: ^2.0.9
  just_audio: ^0.9.8
  record: ^4.4.4
  ffmpeg_kit_flutter: ^6.0.3
  sizer: ^2.0.15
  audio_waveforms: ^1.0.4
  file_picker: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
