name: audio_player
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.9
  just_audio: ^0.9.36
  audio_waveforms: ^1.0.4
  shared_preferences: ^2.1.0
  gap: ^3.0.1
  floor: ^1.4.2
  file_picker: ^6.1.1
  chat_bubbles: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
 
  assets:
    - assets/images/logo.png
    - assets/audios/audio1.mp3
    - assets/audios/audio2.mp3
    - assets/audios/audio3.mp3
    - assets/audios/audio4.mp3

